[package]
name = "myrustproject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clickhouse-rs = { version = "1.1.0-alpha.1" }
tokio = { version = "1", features = ["full"] }
